### ISSUE TITLE
Only works with the first tenant when using locally

### ISSUE THREAD

**Issue by jeffhollan** [yangl900/armclient-go#2]
Potentially change to allow you to specify a setting with the tenant ID you want to use (`armclient set tenantId {tenantId}`) and would use to `acquireAuthToken(tenantId string)` and return the token for that tenant.  

I'm a member of a bunch of tenants and can't use the token without specifying the right one.  Let me know if you've thought about how you'd want to design accounts a part of multiple tenants, and if you have proposal or something similar to above I can potential take a stab at supporting.

Honestly I'd be happy enough in the short term with a flag for tenant Id: `armclient token -tenantId {tenantId}` which I can use to generate bearer tokens for Postman requests.

**Comment by yangl900** [comment]
Yep, I'm aware of this, it actually signed in to all tenants but I only returned tenants[0] :)

I will follow the existing armclient syntax `armclient tenant {id}` to switch. `armclient token -tenant {id}` is a good idea too. I will do this next.

**Comment by yangl900** [comment]
this change 054433d8eee00ef1d6120be1af89a6408e695d2f added the support. I end up using following syntax:

set an active tenant
```
armclient tenant set {tenantId}
```

list all tenants
```
armclient tenant list
```

show current active tenant
```
armclient tenant show
```
