### ISSUE TITLE
Makefile only has linux output

### ISSUE THREAD

**Issue by luanshixia** [yangl900/armclient-go#3]
I am working on adding this as a Homebrew formula. The way it works is calling `make` to build from source. Therefore we need `GOOS=darwin` also.

**Comment by luanshixia** [comment]
I can take this one.

**Comment by yangl900** [comment]
thanks! let me know if you need anything from me.

**Comment by luanshixia** [comment]
https://github.com/yangl900/armclient-go/pull/4

**Comment by yangl900** [comment]
merged :)
