### ISSUE TITLE
Maintain our own Homebrew tap

### ISSUE THREAD

**Issue by luanshixia** [yangl900/armclient-go#5]
The new formula policy for the official tap `homebrew-core` is strict. They enforce this by a check:

```
$ brew audit --new-formula armclient-go
armclient-go:
  * GitHub repository not notable enough (<20 forks, <20 watchers and <50 stars)
  * GitHub repository too new (<30 days old)
Error: 2 problems in 1 formula
```

We can work on earning stars, or alternatively, create and maintain our own tap. A tap is just a simple GitHub repo as a container for formulae. If you have a repo like `yangl900/homebrew-xxx`, users can install the tool using just one line:

```bash
brew install yangl900/xxx/armclient-go
```

Can you please create such a repo, and then I can add the formula (a Ruby file `armclient-go.rb`) into it.

A simple example:
https://github.com/Azure/homebrew-draft

Full documentation:
https://github.com/Homebrew/brew/blob/master/docs/How-to-Create-and-Maintain-a-Tap.md

**Comment by yangl900** [comment]
Ah, i see. I'll create one named `homebrew-armclient-go`, sounds good?

**Comment by luanshixia** [comment]
Yes, it should work. Thanks.

**Comment by yangl900** [comment]
Created the repo: https://github.com/yangl900/homebrew-armclient-go

**Comment by luanshixia** [comment]
Done! Now macOS users can easily install using

```
brew install yangl900/armclient-go/armclient-go
```

I have tested this on both my MacBook Pro and Mac mini.

**Comment by yangl900** [comment]
sweet! thanks for making it happen. :beer:

**Comment by yangl900** [comment]
Updated README also:)
